
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class convo_img extends javax.swing.JFrame {

    /**
     * Creates new form convo_img
     */
    
Code c1=new Code();
 OwnConvolutionCode o1=new OwnConvolutionCode();
public String imageName="";    
public File f=null;
//public String file_path="";

public convo_img() {
    
        initComponents();
         
    }
 public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        file_path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(888, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("         IMAGE CONVOLUTION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 20, 527, 48);

        file_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_pathActionPerformed(evt);
            }
        });
        jPanel1.add(file_path);
        file_path.setBounds(15, 152, 323, 20);

        jButton1.setText("Browse Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(356, 149, 137, 23);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(15, 194, 403, 333);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blur", "EdgeDetection", "EdgeEnhance", "Emboss", "Sharpen", " ", " ", " ", " ", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(377, 582, 158, 20);

        jButton2.setText("Apply");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(401, 624, 118, 23);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(600, 190, 403, 333);

        jLabel4.setBackground(new java.awt.Color(102, 204, 255));
        jLabel4.setRequestFocusEnabled(false);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-30, -20, 980, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(15, 16, 1007, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          JFileChooser chooser=new JFileChooser("D:\\ImageConvolutionGUI\\Images");
        chooser.showOpenDialog(null);
        f =chooser.getSelectedFile();
        file_path.setText(f.getAbsolutePath());
        ImageIcon imgThisImg = new ImageIcon(f.getPath());
        imageName=chooser.getSelectedFile().getName();
        jLabel2.setIcon(imgThisImg);
        StringBuilder sb=new StringBuilder(imgThisImg.toString()).reverse();
       // System.out.println("\\\\\\\\\\\\\\\\"+f.getAbsolutePath());
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void file_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file_pathActionPerformed
 String selectopertion;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        selectopertion=jComboBox1.getSelectedItem().toString();
        
        System.out.println("Select "+selectopertion);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      try{
          selectopertion=jComboBox1.getSelectedItem().toString();
         /*   int kernelSize=c1.ReadKernelSize(selectopertion);
            float[] fileKernelArray=c1.kernelRead(selectopertion);
            System.out.println("kernelSIze="+kernelSize);
            BufferedImage output= c1.execute(kernelSize, fileKernelArray, f);
                File outputfile = new File("D:\\ImageConvolutionGUI\\output\\output Of "+imageName+" for "+selectopertion+".jpg");

          */
          //ownCode implementation
    
            BufferedImage img=null; 
            img=ImageIO.read(new File(f.getAbsolutePath()));

            o1.getRGBValues(img);
 System.out.println("run");

            o1.initializeOutputArray(img);
                                 
            o1.kernelArray=o1.kernelRead(selectopertion);
            o1.computOutputArray(img);
            
            //sBufferedImage output=
            o1.writeImage(img,o1.kernelArray,selectopertion,f.getName());  
            
        /*    
        ImageIO.write(output, "jpg", outputfile); 
        */ImageIcon imgThisImg1 = new ImageIcon(o1.outputFileForIcon.getPath());
        
      
            
        jLabel3.setIcon(imgThisImg1);
     } catch (Exception ex) {
       }    
        
        
        
  
     
        
        
        System.out.println("Done...!");

}
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convo_img.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convo_img.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convo_img.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convo_img.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convo_img().setVisible(true);
            }
        });
    


    }//GEN-LAST:event_jButton2ActionPerformed

   
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField file_path;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
